### ISSUE TITLE
Extension doesn't load

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-checklocalizations-plugin#15]
```
System.BadImageFormatException:  Could not load the file or assembled 'Checklocalizations.dll' or one of its dependencies. [...]Attempted with an incorrect format.
File name: 'Checklocalizations.dll' 
```

![image](https://user-images.githubusercontent.com/1389286/133400337-730b4200-8015-4a30-931f-b65a86653464.png)

[playnite.log](https://github.com/Lacro59/playnite-systemchecker-plugin/files/7168337/playnite.log)

[extensions.log](https://github.com/Lacro59/playnite-systemchecker-plugin/files/7168338/extensions.log)

**Comment by Lacro59** [comment]
Can you try this release?
[playnite-checklocalizations-plugin_2_0.zip](https://github.com/Lacro59/playnite-checklocalizations-plugin/files/7170210/playnite-checklocalizations-plugin_2_0.zip)

**Comment by darklinkpower** [comment]
Working fine 👍👍

![image](https://user-images.githubusercontent.com/1389286/133439488-512e1d3a-3e88-459f-911b-b0c3ee6f578b.png)
