### ISSUE TITLE
Got en error notification

### ISSUE THREAD

**Issue by Andei** [Lacro59/playnite-checklocalizations-plugin#19]
`22-11 19:15:40.850|ERROR|CheckLocalizations#Common:Error on GetLocalizations()|D:\GitHub\Lacro59\playnite-checklocalizations-plugin\source\Clients\SteamLocalizations.cs|46
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   bei Newtonsoft.Json.JsonTextReader.ParseValue()
   bei Newtonsoft.Json.JsonTextReader.Read()
   bei Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   bei Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   bei Playnite.Common.Serialization.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:Zeile 265.
   bei Playnite.Common.DataSerializer.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:Zeile 80.
   bei Playnite.SDK.Data.Serialization.FromJson[T](String json) in C:\projects\playnite\source\PlayniteSDK\Data\DataSerialization.cs:Zeile 310.
   bei CheckLocalizations.Clients.SteamLocalizations.GetLocalizations(Game game) in D:\GitHub\Lacro59\playnite-checklocalizations-plugin\source\Clients\SteamLocalizations.cs:Zeile 46.`

**Comment by Lacro59** [comment]
Do you know the game name with this error?

**Comment by Andei** [comment]
It must have been Max Payne 3, but right now I don't get an error notification anymore
