### ISSUE TITLE
When I delete a game from the list, the plugin crashes

### ISSUE THREAD

**Issue by Slippy2k** [Lacro59/playnite-checklocalizations-plugin#24]
Hello,
If I delete a game from the list, the plugin crashes (in version 2.1.2 + 2.1.1) The v2.1 is bug-free and doesn't crash.
Here my
**playnite.log File:**
`28-05 22:49:34.282|ERROR|PlayniteApplication:Unhandled exception occured.
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei CheckLocalizations.Services.LocalizationsDatabase.Get(Guid Id, Boolean OnlyCache, Boolean Force) in D:\GitHub\Lacro59\playnite-checklocalizations-plugin\source\Services\LocalizationsDatabase.cs:Zeile 87.
   bei CommonPluginsShared.Collections.PluginDatabaseObject`4.Get(Game game, Boolean OnlyCache, Boolean Force) in D:\GitHub\Lacro59\playnite-checklocalizations-plugin\source\playnite-plugincommon\CommonPluginsShared\Collections\PluginDatabaseObject.cs:Zeile 632.
   bei CheckLocalizations.Services.LocalizationsDatabase.SetThemesResources(Game game) in D:\GitHub\Lacro59\playnite-checklocalizations-plugin\source\Services\LocalizationsDatabase.cs:Zeile 333.
   bei CommonPluginsShared.Collections.PluginDatabaseObject`4.Database_ItemCollectionChanged(Object sender, ItemCollectionChangedEventArgs`1 e) in D:\GitHub\Lacro59\playnite-checklocalizations-plugin\source\playnite-plugincommon\CommonPluginsShared\Collections\PluginDatabaseObject.cs:Zeile 142.
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei CommonPlayniteShared.Database.ItemCollection`1.OnCollectionChanged(List`1 addedItems, List`1 removedItems) in D:\GitHub\Lacro59\playnite-checklocalizations-plugin\source\playnite-plugincommon\CommonPlayniteShared\Database\ItemCollection.cs:Zeile 475.
   bei CommonPlayniteShared.Database.ItemCollection`1.Remove(Guid id) in D:\GitHub\Lacro59\playnite-checklocalizations-plugin\source\playnite-plugincommon\CommonPlayniteShared\Database\ItemCollection.cs:Zeile 298.
   bei CommonPluginsShared.Collections.PluginDatabaseObject`4.<>c__DisplayClass57_0.<Remove>b__0() in D:\GitHub\Lacro59\playnite-checklocalizations-plugin\source\playnite-plugincommon\CommonPluginsShared\Collections\PluginDatabaseObject.cs:Zeile 548.
   bei System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   bei System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback, DispatcherPriority priority)
   bei CommonPluginsShared.Collections.PluginDatabaseObject`4.Remove(Guid Id) in D:\GitHub\Lacro59\playnite-checklocalizations-plugin\source\playnite-plugincommon\CommonPluginsShared\Collections\PluginDatabaseObject.cs:Zeile 548.
   bei CommonPluginsShared.Collections.PluginDatabaseObject`4.Remove(Game game) in D:\GitHub\Lacro59\playnite-checklocalizations-plugin\source\playnite-plugincommon\CommonPluginsShared\Collections\PluginDatabaseObject.cs:Zeile 531.
   bei CommonPluginsShared.Collections.PluginDatabaseObject`4.Games_ItemCollectionChanged(Object sender, ItemCollectionChangedEventArgs`1 e) in D:\GitHub\Lacro59\playnite-checklocalizations-plugin\source\playnite-plugincommon\CommonPluginsShared\Collections\PluginDatabaseObject.cs:Zeile 991.
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei Playnite.Database.ItemCollection`1.OnCollectionChanged(List`1 addedItems, List`1 removedItems)
   bei Playnite.Database.ItemCollection`1.Remove(Guid id)
   bei Playnite.Database.GamesCollection.Remove(Guid id)
   bei Playnite.Database.GamesCollection.Remove(Game item)
   bei Playnite.GamesEditor.RemoveGame(Game game)
   bei Playnite.DesktopApp.ViewModels.DesktopAppViewModel.<InitializeCommands>b__287_56(Object a)
   bei Playnite.SDK.RelayCommand`1.Execute(Object parameter)
   bei System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   bei System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   bei System.Windows.Input.KeyEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   bei System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   bei System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   bei System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   bei System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
   bei System.Windows.Interop.HwndSource.WeakEventPreprocessMessage.OnPreprocessMessage(MSG& msg, Boolean& handled)
   bei System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   bei System.Windows.Application.RunDispatcher(Object ignore)
   bei System.Windows.Application.RunInternal(Window window)
   bei System.Windows.Application.Run(Window window)
   bei Playnite.DesktopApp.ProgramEntry.Main(String[] args)
28-05 22:49:34.355|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ExtensionCrashHandlerWindowFactory
`

**Comment by GMRobo** [comment]
Nice to know that my Playnite instance crashing isn't outside the norm. (same version and all)

**Comment by Dorennor** [comment]
Same issue.

**Comment by Heraes-git** [comment]
Same for me. Deleting a game from my library makes Playnite to crash due to this plugin.
