### ISSUE TITLE
Crash with version 1.1

### ISSUE THREAD

**Issue by TheDatadrainer** [Lacro59/playnite-checklocalizations-plugin#3]
Hi.
New version 1.1 crashes when launching Playnite Fullscreen App.
![fullscreenapp_error](https://user-images.githubusercontent.com/56295922/98708456-770c9a00-2381-11eb-803f-3b84a5969620.jpg)
Regards.

**Comment by Lacro59** [comment]
Can you post your Playnite.log?

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-checklocalizations-plugin/commit/7600fe1e99acf7d61da53be75ef11554bce54d24
