### ISSUE TITLE
The plugin doesn't show at all

### ISSUE THREAD

**Issue by Heraes-git** [Lacro59/playnite-checklocalizations-plugin#8]
1. I've installed the last version of your plugin by slidding it into the main window of Playnite. 
2. It asked me to install it, I accepted.
3. Playnite restarted
4. The plugin didn't appear in my "plugin" menu in the settings.
5. I re-slidded the install package, it asked to update, I did it.
6. Playnite restarted, still nothing.

![2020-11-27_02h19m06s_](https://user-images.githubusercontent.com/22033256/100400607-69c8fe00-3057-11eb-813b-e3f25a699ca5.jpg)

**Comment by Heraes-git** [comment]
I found an error message in Playnite :
![2020-11-27_02h57m49s_Playnite DesktopApp](https://user-images.githubusercontent.com/22033256/100402400-6f751280-305c-11eb-9026-bf8629ac80d4.jpg)

The log says : 
> 27-11 03:07:13.352|ERROR|ExtensionFactory:Failed to load plugin: CheckLocalizations
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à CheckLocalizations.CheckLocalizationsSettings..ctor(CheckLocalizations plugin) dans E:\Github\Lacro59\playnite-checklocalizations-plugin\CheckLocalizationsSettings.cs:ligne 49
   à CheckLocalizations.CheckLocalizations..ctor(IPlayniteAPI api) dans E:\Github\Lacro59\playnite-checklocalizations-plugin\CheckLocalizations.cs:ligne 44

**Comment by Lacro59** [comment]
Try to delete files in %AppdData%\ExtensionData\7ce83cfe-7894-4ad9-957d-7249c0fb3e7d.
It's the folder with plugin data.

**Comment by Heraes-git** [comment]
@Lacro59 It didn't work :/

**Comment by Lacro59** [comment]
A new release is published.
Can you test with it?
Thanks.

**Comment by Heraes-git** [comment]
It's even worse : since the last Playnite update, I have several plugins crashing.

![2021-01-08_11h15m53s_Playnite DesktopApp](https://user-images.githubusercontent.com/22033256/104003912-60c56380-51a3-11eb-966f-06f92900b6f4.jpg)

**Comment by Heraes-git** [comment]
Thanks for the updates (Checklocalizations / HowToBeat / GameActivity plugins). I like you. You're a good programmer, you care about your work ;)
